[project]
name = "rageval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Priyanshu Pulak", email = "priyanshu.pulak11@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "deepeval>=4.1.7",
    "langchain-chroma>=1.1.0",
    "langchain-core>=1.5.3",
    "langchain-google-genai>=4.3.3",
    "langchain-openai>=1.4.3",
    "langchain-text-splitters>=1.1.2",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.7.0",
]

[project.scripts]
rageval = "rageval:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
